use_frameworks!

target 'TRULogining_Example' do
  pod 'TRULogining', :path => '../'
  pod 'TRUNetworking', :path => '../../TRUNetworking'

  target 'TRULogining_Tests' do
    inherit! :search_paths

    
  end
end
